# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dist_nn.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'dist_nn.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rdist_nn.proto\x12\x0cgrpc_dist_nn\"\x15\n\x03Row\x12\x0e\n\x06values\x18\x01 \x03(\x01\")\n\x06Matrix\x12\x1f\n\x04rows\x18\x01 \x03(\x0b\x32\x11.grpc_dist_nn.Row2E\n\x0cLayerService\x12\x35\n\x07Process\x12\x14.grpc_dist_nn.Matrix\x1a\x14.grpc_dist_nn.Matrixb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dist_nn_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROW']._serialized_start=31
  _globals['_ROW']._serialized_end=52
  _globals['_MATRIX']._serialized_start=54
  _globals['_MATRIX']._serialized_end=95
  _globals['_LAYERSERVICE']._serialized_start=97
  _globals['_LAYERSERVICE']._serialized_end=166
# @@protoc_insertion_point(module_scope)
